import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GlobalContextProvider } from "@/Context/store";
import { Toaster } from "@/components/ui/toaster";
import { useProfileStore } from "@/lib/store/profile";
import { getProfile } from "@/lib/action";
import { CookiesProvider } from "next-client-cookies/server";
import { Separator } from "@/components/ui/separator";
import Nav from "@/components/Nav/Nav";
import Profile from "@/components/Profile";
import { Suspense } from "react";
import { TooltipProvider } from "@/components/ui/tooltip";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TooltipProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter.variable
          )}
        >
          <Toaster />

          <GlobalContextProvider>{children}</GlobalContextProvider>
        </body>
      </TooltipProvider>
    </html>
  );
}
